# Generated by Django 2.1.2 on 2018-11-22 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actress_bid', models.CharField(max_length=20)),
                ('actress_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_bid', models.CharField(max_length=20)),
                ('production_name', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('official_review', models.TextField()),
                ('lab_review', models.TextField()),
                ('actresses', models.ManyToManyField(to='irrumatio_lab.Actress')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionAddons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_img', models.CharField(max_length=200)),
                ('dmm_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irrumatio_times', models.IntegerField()),
                ('irrumatio_cum_times', models.IntegerField()),
                ('irrumatio_throat_cum_times', models.IntegerField()),
                ('irrumatio_duration_min', models.IntegerField()),
                ('spit_amount', models.SmallIntegerField()),
                ('spit_sound', models.SmallIntegerField()),
                ('puke_reaction', models.SmallIntegerField()),
                ('speed', models.SmallIntegerField()),
                ('depth', models.SmallIntegerField()),
                ('cock_level', models.SmallIntegerField()),
                ('puke_amount', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_img_link', models.CharField(max_length=200)),
                ('production_addons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrumatio_lab.ProductionAddons')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='production_addons',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='irrumatio_lab.ProductionAddons'),
        ),
        migrations.AddField(
            model_name='production',
            name='production_evaluation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='irrumatio_lab.ProductionEvaluation'),
        ),
    ]
