# Generated by Django 2.1.2 on 2018-11-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrumatio_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionevaluation',
            name='actress_mark',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productionevaluation',
            name='overall_mark',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='lab_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='official_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionaddons',
            name='cover_img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productionaddons',
            name='dmm_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productionevaluation',
            name='cock_level',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productionevaluation',
            name='depth',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productionevaluation',
            name='irrumatio_cum_times',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productionevaluation',
            name='irrumatio_duration_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productionevaluation',
            name='irrumatio_throat_cum_times',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productionevaluation',
            name='irrumatio_times',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productionevaluation',
            name='puke_amount',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productionevaluation',
            name='puke_reaction',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productionevaluation',
            name='speed',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productionevaluation',
            name='spit_amount',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productionevaluation',
            name='spit_sound',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
