# Generated by Django 2.1.2 on 2018-11-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrumatio_lab', '0002_auto_20181122_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionevaluation',
            name='overall_mark',
            field=models.SmallIntegerField(blank=True, default=0, help_text='总评', null=True),
        ),
    ]
