# Generated by Django 2.1.2 on 2018-11-22 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irrumatio_lab', '0003_auto_20181122_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActressComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.SmallIntegerField(blank=True, null=True)),
                ('actress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrumatio_lab.Actress')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrumatio_lab.Production')),
            ],
        ),
    ]
