# Generated by Django 2.1.2 on 2018-11-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrumatio_lab', '0004_actresscomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actresscomment',
            name='actress',
        ),
        migrations.RemoveField(
            model_name='actresscomment',
            name='production',
        ),
        migrations.DeleteModel(
            name='ActressComment',
        ),
    ]
